Document: amxa-desktop-extra
Title: Debian amxa-desktop-extra Manual
Author: <insert document author here>
Abstract: This manual describes what amxa-desktop-extra is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/amxa-desktop-extra/amxa-desktop-extra.sgml.gz

Format: postscript
Files: /usr/share/doc/amxa-desktop-extra/amxa-desktop-extra.ps.gz

Format: text
Files: /usr/share/doc/amxa-desktop-extra/amxa-desktop-extra.text.gz

Format: HTML
Index: /usr/share/doc/amxa-desktop-extra/html/index.html
Files: /usr/share/doc/amxa-desktop-extra/html/*.html
